### PR TITLE
Remove the need for skopeo

### PR DESCRIPTION
**Pull request by dcermak**
pytest_container can now inspect containers directly. Thereby we do not need to rely on skopeo for the tests anymore

### CODE REVIEW

**Review by jlausuch — APPROVED** [review]
Nice! 1 dependency less.

**Comment by dcermak** [comment]
Looks like the registry is currently not working :-/
Let's wait a bit and then restart the CI so that the tests are green again.

**Comment by dcermak** [comment]
Looks like we had pcp tagged at version `5.2.2` and it just received a patch level bump to `5.2.5`. I have thus changed the version to `5`, so that we can avoid needlessly having to bump the version.

**Comment by dcermak** [comment]
The metadata test failure is expected as the pcp container hasn't been released with this version yet

**Pull request merged**
