### PR TITLE
Add rust1.62

### PR DESCRIPTION
**Pull request by grisu48**
Add the container definition for rust 1.62

### CODE REVIEW

**Review by dcermak — APPROVED** [review]

**Review by dcermak — CHANGES_REQUESTED** [review]
The Rust container needs to be added to the metadata tests as well.

**Comment by grisu48** [comment]
> The Rust container needs to be added to the metadata tests as well.

Can you point me to the location? https://github.com/SUSE/BCI-tests/blob/main/tests/test_metadata.py#L62 includes `RUST_CONTAINERS` and therefore the new one as well and I don't see any other places that need to be edited.

**Comment by dcermak** [comment]
> Can you point me to the location? https://github.com/SUSE/BCI-tests/blob/main/tests/test_metadata.py#L62 includes `RUST_CONTAINERS` and therefore the new one as well and I don't see any other places that need to be edited.

Argh, sorry, I was wrong, the containers got added.
However, the metadata test currently fails because the image has not been published yet. I.e. your openQA test run before publishing will fail as well. Depending on how you handle test failures, you might want to add an xfail.

**Comment by grisu48** [comment]
> Argh, sorry, I was wrong, the containers got added. However, the metadata test currently fails because the image has not been published yet. I.e. your openQA test run before publishing will fail as well. Depending on how you handle test failures, you might want to add an xfail.

A local test run succeeded and I can also see the rust image in [CR](https://build.suse.de/package/show/SUSE:SLE-15-SP4:Update:CR/rust-1.62-image). Not entirely sure bit in my view I don't see any obstacles here :thinking:

**Comment by dcermak** [comment]
Felix Niederwanger ***@***.***> writes:

>> Argh, sorry, I was wrong, the containers got added. However, the metadata test currently fails because the image has not been published yet. I.e. your openQA test run before publishing will fail as well. Depending on how you handle test failures, you might want to add an xfail.
>
> A local test run succeeded and I can also see the rust image in [CR](https://build.suse.de/package/show/SUSE:SLE-15-SP4:Update:CR/rust-1.62-image). Not entirely sure bit in my view I don't see any obstacles here :thinking: 

Did you run the metadata test as well? Because that one will fail, as it
tries to fetch the image from registry.suse.com

**Comment by grisu48** [comment]
> Did you run the metadata test as well? Because that one will fail, as it tries to fetch the image from registry.suse.com

You are right!

```
E       AssertionError: Unexpected exit code 125 for CommandResult(command=b'podman pull registry.suse.com/bci/rust:1.62', exit_status=125, stdout=None, stderr=b'Trying to pull registry.suse.com/bci/rust:1.62...\nError: initializing source docker://registry.suse.com/bci/rust:1.62: reading manifest 1.62 in registry.suse.com/bci/rust: manifest unknown: manifest unknown\n')
E       assert 125 in [0]
E        +  where 125 = CommandResult(command=b'podman pull registry.suse.com/bci/rust:1.62', exit_status=125, stdout=None, stderr=b'Trying to pull registry.suse.com/bci/rust:1.62...\nError: initializing source docker://registry.suse.com/bci/rust:1.62: reading manifest 1.62 in registry.suse.com/bci/rust: manifest unknown: manifest unknown\n').rc

tests/test_metadata.py:443: AssertionError
```

I'm looking into an option how to mark this test as expected to fail.

**Comment by grisu48** [comment]
If this is a transient failure only happening at the first time until it is released, I would be totally OK to merge it and manually approve the first test runs. That might be better than introducing a temporary approval mechanism, that will be removed after the first release.

**Pull request merged**
