### PR TITLE
Fixup metadata tests for LTSS containers

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by dirkmueller** [comment]
(all validated manually on a system without the broken conmon)

**Review by dcermak — CHANGES_REQUESTED** [review]
The base tests are broken because they import the now gone variable `LTSS_CONTAINERS`. Same issue breaks the documentation.

**Comment by dcermak** [comment]
The SP4 LTSS tests are all red as the base-sp4-ltss image cannot be found. @dirkmueller Is your token valid for SP4 as well or has the image not been released yet?

**Comment by dirkmueller** [comment]
> The SP4 LTSS tests are all red as the base-sp4-ltss image cannot be found. @dirkmueller Is your token valid for SP4 as well or has the image not been released yet?

the image is released. I guess we need a better token. it was on my todo for today.

**Review by grisu48 — APPROVED** [review]

**Pull request merged**
