### PR TITLE
Update golang-openssl to stable and oldstable

### PR DESCRIPTION
**Pull request by grisu48**
Update the golang-*-openssl tests to being now processed as go_stable-openssl and go_oldstable-openssl.

### CODE REVIEW

**Comment by grisu48** [comment]
I'm stuck at:

```
>       assert not orphaned_packages.difference(known_orphaned_packages)
E       AssertionError: assert not {'go1.19-openssl', 'go1.19-openssl-doc', 'go1.19-openssl-race'}
E        +  where {'go1.19-openssl', 'go1.19-openssl-doc', 'go1.19-openssl-race'} = <built-in method difference of set object at 0x7ff98c2c65e0>({'kubic-locale-archive', 'nodejs16', 'npm16', 'postgresql14', 'postgresql14-server', 'skelcd-EULA-bci', ...})
E        +    where <built-in method difference of set object at 0x7ff98c2c65e0> = {'go1.19-openssl', 'go1.19-openssl-doc', 'go1.19-openssl-race', 'kubic-locale-archive', 'skelcd-EULA-bci', 'sles-release'}.difference

tests/test_all.py:185: AssertionError
```

**Comment by dirkmueller** [comment]
@grisu48 can you retry? the go1.19-openssl packages have been added.

**Comment by grisu48** [comment]
> @grisu48 can you retry? the go1.19-openssl packages have been added.

test runs restarted.

**Comment by grisu48** [comment]
@dirkmueller same issue. Also, BCI tests are not starting, AFAICS there is still an issue in the code itself:

```
phoenix@racetrack-7290:~/QEC/BCI-tests> source .venv/bin/activate
(.venv) phoenix@racetrack-7290:~/QEC/BCI-tests> tox -e all -- -rxX -n auto -k "golang_oldstable-openssl"
.pkg: _optional_hooks> python /usr/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /usr/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: prepare_metadata_for_build_wheel> python /usr/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_sdist> python /usr/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
all: install_package> python -I -m pip install --force-reinstall --no-deps /home/phoenix/QEC/BCI-tests/.tox/.tmp/package/32/bci-tester-0.1.dev898+gf66adf7.tar.gz
all: commands[0]> pytest -vv tests/test_all.py --junitxml=/home/phoenix/QEC/BCI-tests/junit_all.xml -rxX -n auto -k golang_oldstable-openssl
======================================================= test session starts ========================================================
platform linux -- Python 3.10.13, pytest-7.4.2, pluggy-1.3.0 -- /home/phoenix/QEC/BCI-tests/.tox/all/bin/python
cachedir: .tox/all/.pytest_cache
rootdir: /home/phoenix/QEC/BCI-tests
configfile: pyproject.toml
plugins: xdist-3.3.1, testinfra-9.0.0, rerunfailures-12.0, pytest_container-0.2.0
8 workers [0 items]     
scheduling tests via LoadScheduling

---------------------------------- generated xml file: /home/phoenix/QEC/BCI-tests/junit_all.xml -----------------------------------
====================================================== no tests ran in 1.42s =======================================================
all: exit 5 (1.90 seconds) /home/phoenix/QEC/BCI-tests> pytest -vv tests/test_all.py --junitxml=/home/phoenix/QEC/BCI-tests/junit_all.xml -rxX -n auto -k golang_oldstable-openssl pid=11315
.pkg: _exit> python /usr/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  all: FAIL code 5 (7.69=setup[5.79]+cmd[1.90] seconds)
  evaluation failed :( (7.93 seconds)

```

**Comment by dirkmueller** [comment]
@grisu48 two issues: you need to use "-m" to filter by marker and you should use the `tox -e go` for the go tests

**Comment by dirkmueller** [comment]
For me, with your branch (rebased on top of latest master) both -e all and -e go are working fine.

**Comment by grisu48** [comment]
Rebase resolved the issue, all good from my side :+1:

**Pull request merged**
