### PR TITLE
Python 3.11 is also available for SP4 now

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by dcermak** [comment]
> Python 3.11 is also available for SP4 now

Since when?

**Comment by dirkmueller** [comment]
> > Python 3.11 is also available for SP4 now
> Since when?

as of when I created the pr. it was released friday afternoon.

**Review by dcermak — CHANGES_REQUESTED** [review]
The Python 3.11 container is missing in the list `L3_CONTAINERS`.

**Review by dcermak — APPROVED** [review]
LGTM, thanks! And the CI is happy :tada:

**Pull request merged**
