### PR TITLE
Enable BCI Base for 15-SP5 for Public Beta

### PR DESCRIPTION
**Pull request by jlausuch**

### CODE REVIEW

**Comment by dcermak** [comment]
Just the base container and no others?

**Comment by jlausuch** [comment]
> Just the base container and no others?

Others will come after GA if I'm not mistaken..

**Comment by jlausuch** [comment]
> Just the base container and no others?

Ok, let me enable all the rest in one shot, anyway, we can enable/disable the openQA pipeline for those containers.

**Review by dcermak — CHANGES_REQUESTED** [review]
This won't work for minimal, micro, busybox and init, they are set to be available for 15.4 only.

**Review by dcermak — CHANGES_REQUESTED** [review]
init is missing

**Review by dcermak — CHANGES_REQUESTED** [review]
```
tests/test_init.py:12: in <module>
    from bci_tester.data import INIT_CONTAINER
bci_tester/data.py:327: in <module>
    INIT_CONTAINER = create_BCI(
bci_tester/data.py:193: in create_BCI
    raise ValueError(
E   ValueError: Invalid os version for a language or application stack container: 15.5
```

**Review by dcermak — CHANGES_REQUESTED** [review]
all the busybox tests are skipped due to the global pytestmark in test_busybox.py

**Pull request merged**
