### PR TITLE
Rely on awk and procps being installed in the openjdk containers

### PR DESCRIPTION
**Pull request by dirkmueller**
This improves the test coverage here to ensure the packages are not forgotten.

Depends-On: https://github.com/SUSE/BCI-dockerfile-generator/pull/1349

### CODE REVIEW

**Review by dcermak — CHANGES_REQUESTED** [review]
Blocking as it breaks the CI at the moment. We can merge it once we fixed the containers.

**Comment by dirkmueller** [comment]
> Blocking as it breaks the CI at the moment. We can merge it once we fixed the containers.

containers are fixed.

**Comment by dcermak** [comment]
Looks like there's a new issue with cassandra that is unrelated to this PR:
```
DEBUG    testinfra:base.py:328 RUN CommandResult(backend=<testinfra.backend.docker.DockerBackend object at 0x7f1dfe378fa0>, exit_status=0, command=b"docker exec 68609f79d7928c9c1a1932d0507f043278527c3b5d6c078fac60ecd24a899555 /bin/sh -c 'cat -- /var/log/cassandra.log'", _stdout=b'Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer).\n', _stderr=b'')
```

**Comment by dirkmueller** [comment]
> Looks like there's a new issue with cassandra that is unrelated to this PR:
> 
> ```
> DEBUG    testinfra:base.py:328 RUN CommandResult(backend=<testinfra.backend.docker.DockerBackend object at 0x7f1dfe378fa0>, exit_status=0, command=b"docker exec 68609f79d7928c9c1a1932d0507f043278527c3b5d6c078fac60ecd24a899555 /bin/sh -c 'cat -- /var/log/cassandra.log'", _stdout=b'Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer).\n', _stderr=b'')
> ```

no, it's related. the issue is that cassandra needs `awk` at runtime, so the patch doesn't work. I'm still undecided what to do about it. we could install it in the openjdk container or not merge this PR.

**Review by alexandrevicenzi — APPROVED** [review]

**Pull request merged**
