### PR TITLE
Install dapper via download for go < 1.17 and don't build rancher on ppc64

### PR DESCRIPTION
**Pull request by dcermak**
Related ticket: https://progress.opensuse.org/issues/117373

### CODE REVIEW

**Review by grisu48 — APPROVED** [review]
LGTM, thanks for the quick fix.

**Comment by grisu48** [comment]
@dcermak Could you put the following please in the PR description for future reference?

Related ticket: https://progress.opensuse.org/issues/117373

**Comment by dcermak** [comment]
@grisu48 Can you try this PR on a SLE 15 host please?

**Comment by grisu48** [comment]
Test run with this branch: https://duck-norris.qam.suse.de/tests/10874

**Comment by grisu48** [comment]
VR passing.

**Review by grisu48 — APPROVED** [review]

**Comment by grisu48** [comment]
VR for ppc64le: https://openqa.suse.de/tests/9630159

**Pull request merged**
