### PR TITLE
Run container tests in parallel

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Review by dcermak — DISMISSED** [review]
I thought we were already doing that :see_no_evil:

**Comment by dirkmueller** [comment]
> I thought we were already doing that see_no_evil

In a way we do that by running the test groups in parallel. the gain is not so much as the jobs take most of their time in setting up the ci job rather than running the tests. I think we need to group them more to have a better throughput. I'll play with that when I have some time.

**Comment by dcermak** [comment]
> it does hang though if there are failures. which is not good :/

This looks like a bug in the locking of pytest_container, I'll take a look.

**Comment by dcermak** [comment]
Should be fixed via https://github.com/dcermak/pytest_container/pull/135

**Comment by dcermak** [comment]
Looks like the hang is gone

**Review by dcermak — APPROVED** [review]
This LGTM, is this ready to be merged @dirkmueller?

**Pull request merged**
