### PR TITLE
Add python 3.11 unit testing

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Review by dcermak — CHANGES_REQUESTED** [review]
Blocked by https://github.com/SUSE/BCI-dockerfile-generator/pull/304

**Comment by dirkmueller** [comment]
Please don't request changes when you don't request changes ;) I moved it into a draft until the python 3.11 container has been released.

**Comment by dcermak** [comment]
Dirk Mueller ***@***.***> writes:

> Please don't request changes when you don't request changes ;) I moved it into a draft until the python 3.11 container has been released.

There is literally no other way to block a pull request from getting
merged, unless I frag your branch or just close it...

**Comment by dirkmueller** [comment]
> Dirk Mueller ***@***.***> writes:

> There is literally no other way to block a pull request from getting merged, unless I frag your branch or just close it...

you can set it to "draft" for example, or trust me that if the part I'm changing is not passing the ci, I wouldn't merge it ;)

**Comment by dirkmueller** [comment]
python 3.11 BCI container has been released, so we can review this now.

**Review by dcermak — APPROVED** [review]

**Pull request closed without merging**
