### PR TITLE
Verify that the expected groups are created in the init container

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by dcermak** [comment]
`systemd-network` is not in the Tumbleweed init container

**Comment by dirkmueller** [comment]
well, the question if thats a testsuite problem or a container problem

**Comment by dirkmueller** [comment]
I've removed it for now

**Review by dcermak — CHANGES_REQUESTED** [review]
Fails on Tumbleweed with:
```
getent group systemd-timesync
```
That group also does not appear to exist in the distro anymore:
```
dnf rq --whatprovides "group(systemd-timesync)"
```
finds nothing.

**Comment by dirkmueller** [comment]
it's not clear this serves any value. lets not bother with it.

**Pull request closed without merging**
